apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: springfield-csi
spec:
  storageCapacity: true
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
