apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.name }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.image.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ .Values.image.name }}
    spec:
        containers:
          - name: {{ .Values.image.name }} 
            image: "ghcr.io/trgill/springfield-csi-driver:0.0.1"
            ports:
            - containerPort: 8080
            env:
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
        imagePullSecrets:
          - name: springfield-csi-secret


