
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: springfield.csi.redhat.com
  labels:
    app.kubernetes.io/name: springfield-csi-driver
spec:
  attachRequired: true
  podInfoOnMount: false